# Generated by Django 3.1.2 on 2021-05-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210501_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
